//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Eclo_STM32F4.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_Eclo_STM32F4_Eclo_STM32F4_Math::NativeSuperComplicatedCalculation___STATIC__R8__R8,
    NULL,
    NULL,
    Library_Eclo_STM32F4_Eclo_STM32F4_Utilities::NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Eclo_STM32F4 =
{
    "Eclo.STM32F4", 
    0x4B135D6F,
    method_lookup
};

