//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Eclo_STM32F4.h"
#include "Eclo_STM32F4_Eclo_STM32F4_Math.h"

using namespace Eclo::STM32F4;


HRESULT Library_Eclo_STM32F4_Eclo_STM32F4_Math::NativeSuperComplicatedCalculation___STATIC__R8__R8( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        double param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_double( stack, 0, param0 ) );

        double retVal = Math::NativeSuperComplicatedCalculation( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
        SetResult_double( stack, retVal );

    }
    TINYCLR_NOCLEANUP();
}
