//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _ECLO_STM32F4_H_
#define _ECLO_STM32F4_H_

#include <TinyCLR_Interop.h>
struct Library_Eclo_STM32F4_Eclo_STM32F4_Math
{
    TINYCLR_NATIVE_DECLARE(NativeSuperComplicatedCalculation___STATIC__R8__R8);

    //--//

};

struct Library_Eclo_STM32F4_Eclo_STM32F4_Utilities
{
    static const int FIELD_STATIC___hardwareSerial = 0;

    TINYCLR_NATIVE_DECLARE(NativeGetHardwareSerial___STATIC__VOID__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Eclo_STM32F4;

#endif  //_ECLO_STM32F4_H_
